// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
init()
{
	// Core //
	mickey\varcache::init();
	thread mickey\events::init();
	//  //
	
	// Plugin handler //  
	thread plugins\plugins::init();
	//  //
		
	// welcome //  
	thread new\_welcome::init();
	//  //	
	
	// misc //  
	thread mickey2\misc::init();
	//  //
	
	// lan //  
	thread mickey2\_languages::init();
	//  //
	
	// cheat2 //  
	thread duffman\_anticheat::init();
	//  //
	
	// anticheat //
	thread mickey\anticheat::init();
	// //
	
	// anitiafk //
	thread mickey\antiafk::init();
	// //
		
	// fpsfov //
	thread mickey2\togglebinds::init();
	//  //
	
	// bots //
	thread mickey\bots::init();
	//  //
	
	// geo //
	thread mickey\geo::init();
	// //
	
	// VIP //
	thread mickey\vip::init();
	//  //
	
	// Welcome //
	thread mickey\welcome::init();
	//  //
	
	// Balance //
	thread mickey\balance::init();
	//  //
	
	// Admin system //
	thread mickey\admin::init();
	thread mickey\cmd_launcher::init();
	//  //
	
	// Fx //
	thread mickey\fx::init();
	//  //
	
	// sec //
	//thread mickey\sec::init();
	//  //
	
	// Credits //
	thread mickey\credits::setUp();
	//  //
	
	//thread dev();
	
	// Splash system //
	if( level.leiizko_dvars[ "scr_splashes" ] )
		thread mickey\splash::init();
	//  //
		
	// Killcam //
	if( level.leiizko_dvars[ "scr_final_killcam" ] )
		thread mickey\killcam_settings::init();
	//  //
}


// This is used for scriptfunctions in cod4x server. 
startGame()
{
	thread plugins\commands::init();
}

dev()
{
	level.dev = newHudElem();
	level.dev setText( "This build is EXPERIMENTAL and is considered unstable!" );
	level.dev.alpha = 1;
	level.dev.glowAlpha = 1;
	level.dev.horzAlign = "center";
	level.dev.vertAlign = "top";
	level.dev.glowColor = ( 0.88627, 0.40321, 0.16078 );
	level.dev.archived = false;
	level.dev.alignX = "center";
	level.dev.alignY = "top";
	level.dev.x = 0;
	level.dev.y = 5;
	level.dev.fontscale = 1.6;
	level.dev.color = ( 1, 1, 1 );
	
	level waittill("game_ended");
	
	if( isDefined( level.dev ) )
		level.dev destroy();
}