// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
#include mickey\utility;

init()
{
	addVard( "scr_promod_text", "string", "" );
	addVard( "scr_credit_text", "string", "Thank you for playing ^5PROMOD ^1LIVE ^2v.2.20^1 test" );
	addVard( "scr_welcome_text", "string", "" );
	addVard( "scr_menu_message", "string", "" );
	addVard( "vip_clan_name", "string", "www.virusgaming.xyz" );
	addVard( "scr_start_text", "string", "" );
	addVard( "scr_splashes", "int", 1, 0, 1 );
	addVard( "scr_final_killcam", "int", 1, 0, 1 );
	addVard( "scr_mapvote", "int", 1, 0, 1 );
	addVard( "scr_welcome_geo", "int", 1, 0, 1 );
	addVard( "scr_welcome_public", "int", 1, 0, 1 );
	addVard( "cmd_enable", "int", 1, 0, 1 );
	addVard( "fx_enable", "int", 1, 0, 1 );
	addVard( "fx_knife_blood", "int", 1, 0, 1 );
	addVard( "fx_death_pool", "int", 1, 0, 1 );
	addVard( "fx_death_cash", "int", 1, 0, 1 );
	addVard( "fx_screen_blood", "int", 1, 0, 1 );
	addVard( "music", "int", 1, 0, 1 );
	addVard( "end_music", "int", 1, 0, 1 );
	addVard( "random_rotation", "int", 1, 0, 1 );
	addVard( "promod_licence", "string", "Contact ^5{MiCkEy}.ViRuS ^7for valid licence." );
	////////////////////////////////////////
	// TODO: Mapvote ??                   //
	addVard( "mapvote", "int", 1, 0, 1 );
	////////////////////////////////////////
	addVard( "music_num", "int", 12, 0, 24 );
	
	// This is used to check whether we should welcome the player or not. 
	if( !isDefined( game["game_start_time"] ) )
		game["game_start_time"] = getTime();
}