// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
main()
{
	setDvar("bg_bobMax",0);
	setDvar("player_sustainAmmo",0);
	setDvar("player_throwBackInnerRadius",0);
	setDvar("player_throwBackOuterRadius",0);
	setDvar("loc_warnings",0);

	game["allies_assault_count"]=0;
	game["allies_specops_count"]=0;
	game["allies_demolitions_count"]=0;
	game["allies_sniper_count"]=0;
	game["axis_assault_count"]=0;
	game["axis_specops_count"]=0;
	game["axis_demolitions_count"]=0;
	game["axis_sniper_count"]=0;
	game["promod_timeout_called"]=false;
	game["promod_in_timeout"]=0;
	game["allies_timeout_called"]=0;
	game["axis_timeout_called"]=0;
	game["promod_first_readyup_done"]=0;
	game["PROMOD_VERSION"]= level.leiizko_dvars[ "scr_promod_text" ];
}