// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
init()
     {
	level.callbackiPrintSmall = ::iPrintSmall;
	level.callbackiPrintBig = ::iPrintBig;
	level.callbackGetLangString = ::getLangString;
	//mickey2\_common::addConnectThread(::PlayerConnect);
	}
 
 iPrintSmall(string,srch0,rep0,srch1,rep1,srch2,rep2,srch3,rep3,srch4,rep4,srch5,rep5,srch6,rep6) {
	if(isDefined(self) && isplayer(self))
		self iPrintln(self getLangString(string,srch0,rep0,srch1,rep1,srch2,rep2,srch3,rep3,srch4,rep4,srch5,rep5,srch6,rep6));
	else {
		players = GetEntArray("player","classname");
		for(i=0;i<players.size;i++)
			players[i] iPrintln(players[i] getLangString(string,srch0,rep0,srch1,rep1,srch2,rep2,srch3,rep3,srch4,rep4,srch5,rep5,srch6,rep6));
	}
}

iPrintBig(string,srch0,rep0,srch1,rep1,srch2,rep2,srch3,rep3,srch4,rep4,srch5,rep5,srch6,rep6) {
	if(isDefined(self) && isplayer(self))
		self iPrintlnBold(self getLangString(string,srch0,rep0,srch1,rep1,srch2,rep2,srch3,rep3,srch4,rep4,srch5,rep5,srch6,rep6));
	else {
		players = GetEntArray("player","classname");
		for(i=0;i<players.size;i++)
			players[i] iPrintlnBold(players[i] getLangString(string,srch0,rep0,srch1,rep1,srch2,rep2,srch3,rep3,srch4,rep4,srch5,rep5,srch6,rep6));
	}

}

Replace_Variables( str, what, to )  {
	outstring="";
	if( !isString(what) ) {
		outstring = str;
		for(i=0;i<what.size;i++) {
			if(isDefined(to[i]))
				r = to[i];
			else
				r ="UNDEFINED["+what[i]+"]";
			outstring = Replace_Variables(outstring, what[i], r); 
		}
	}
	else {
		what = "$$" + what + "$$";
		for(i=0;i<str.size;i++) {
			if(GetSubStr(str,i,i+what.size )==what) {
				outstring+=to;
				i+=what.size-1;
			}
			else
				outstring+=GetSubStr(str,i,i+1);
		}
	}
	return outstring;
}

getLangString(alias,srch0,rep0,srch1,rep1,srch2,rep2,srch3,rep3,srch4,rep4,srch5,rep5,srch6,rep6) { //why didnt use array? :D
	if(!isDefined(self.pers["country"]))
		self.pers["country"] = "EN";
	if(!isDefined(alias) || !isDefined(self)) return "";	
	if(!isPlayer(self)) {
		array = [];
		players = GetEntArray("player","classname");
		for(i=0;i<players.size;i++) {
			array[i] = players[i] getLangString(alias,srch0,rep0,srch1,rep1,srch2,rep2,srch3,rep3,srch4,rep4,srch5,rep5,srch6,rep6);
		}
		return array;
	}
	search = [];
	replace = [];
	if(isDefined(srch0) && isDefined(rep0)) { 
		search[0] = srch0; replace[0] = rep0; 
		if(isDefined(srch1) && isDefined(rep1)) { 
			search[1] = srch1; replace[1] = rep1; 
			if(isDefined(srch2) && isDefined(rep2)) { 
				search[2] = srch2; replace[2] = rep2; 
				if(isDefined(srch3) && isDefined(rep3)) {
					search[3] = srch3; replace[3] = rep3; 
					if(isDefined(srch4) && isDefined(rep4)) { 
						search[4] = srch4; replace[4] = rep4; 
						if(isDefined(srch5) && isDefined(rep5)) { 
							search[5] = srch5; replace[5] = rep5; 
							if(isDefined(srch6) && isDefined(rep6)) { 
								search[6] = srch6; replace[6] = rep6; } } } } } } } // I know this looks ugly but saves resources cuz we stop checking them if we got nothing before
	
	if(isDefined(level.lang[self.pers["country"]])) {
		if(isDefined(level.lang[self.pers["country"]][alias])) {
			if(!isString(level.lang[self.pers["country"]][alias]) || !isSubStr(level.lang[self.pers["country"]][alias],"$$"))
				return level.lang[self.pers["country"]][alias]; // we need this part to make it work with label strings
			else
				return Replace_Variables(level.lang[self.pers["country"]][alias],search,replace);
		}
		//else
		//	logprint("WARNING couldn't find alias '" + alias + "' in " + self.pers["country"] + "\n");
	}
	return Replace_Variables(level.lang["EN"][alias],search,replace);
}

Lang(lang,alias,string) { 
	level.lang[lang][alias] = string;
}

LanguageDefinition(county,lang) {
	level.lang[county] = level.lang[lang];
}