// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
main(){maps\mp\_load::main();maps\mp\_compass::setupMiniMap("compass_map_mp_cargoship");game["allies"]="sas";game["axis"]="russian";game["attackers"]="allies";game["defenders"]="axis";game["allies_soldiertype"]="woodland";game["axis_soldiertype"]="woodland";level.sunlight=1.3;}