// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
main(){maps\mp\_load::main();maps\mp\_compass::setupMiniMap("compass_map_mp_crash");game["allies"]="marines";game["axis"]="opfor";game["attackers"]="allies";game["defenders"]="axis";game["allies_soldiertype"]="desert";game["axis_soldiertype"]="desert";level.sunlight=1.3;}